name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Specify the .NET version

      - name: Build
        run: dotnet publish EarthQuake.Desktop/EarthQuake.Desktop.csproj -c Release -r ${{ matrix.target }} --self-contained -p:PublishSingleFile=true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: |
            **/bin/Release/net8.0/${{ matrix.target }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Pack build artifacts
        run: |
          mkdir -p $GITHUB_WORKSPACE/release-assets
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-win-x64.zip artifacts/win-x64-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-linux-x64.zip artifacts/linux-x64-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-osx-x64.zip artifacts/osx-x64-build

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          
      - name: Edit permission
        run: chmod 777 $GITHUB_WORKSPACE/release-assets/EarthQuake-win-x64.zip
      
      - name: Debug Artifacts
        run: |
          echo "Checking if file exists:"
          ls -la $GITHUB_WORKSPACE/release-assets
          if [ -f "$GITHUB_WORKSPACE/release-assets/EarthQuake-win-x64.zip" ]; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi
      
      - name: Upload Windows Asset
        uses: svenstaro/upload-release-action@v2 
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/release-assets/EarthQuake-win-x64.zip
          asset_name: EarthQuake-win-x64.zip
          overwrite: true
          tag: ${{ github.ref }}
          