name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Specify the .NET version

      - name: Build
        run: dotnet publish EarthQuake.Desktop/EarthQuake.Desktop.csproj -c Release -r ${{ matrix.target }} --self-contained -p:PublishSingleFile=true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: |
            **/bin/Release/net8.0/${{ matrix.target }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: |
            win-x64-build
            linux-x64-build
            osx-x64-build

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            **/bin/Release/net8.0/win-x64/*
            **/bin/Release/net8.0/linux-x64/*
            **/bin/Release/net8.0/osx-x64/*
          asset_name: |
            EarthQuake-win-x64.zip
            EarthQuake-linux-x64.zip
            EarthQuake-osx-x64.zip
          asset_content_type: application/zip