name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [win-x64, win-x86, linux-x64, linux-arm, linux-arm64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Specify the .NET version

      - name: Build
        run: dotnet publish EarthQuake.Desktop/EarthQuake.Desktop.csproj -c Release -r ${{ matrix.target }} --self-contained -p:PublishSingleFile=true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: |
            **/bin/Release/net8.0/${{ matrix.target }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Pack build artifacts
        run: |
          mkdir -p $GITHUB_WORKSPACE/release-assets
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-win-x64.zip artifacts/win-x64-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-win-x86.zip artifacts/win-x86-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-linux-x64.zip artifacts/linux-x64-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-linux-arm.zip artifacts/linux-arm-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-linux-arm64.zip artifacts/linux-arm64-build
          zip -r $GITHUB_WORKSPACE/release-assets/EarthQuake-osx-x64.zip artifacts/osx-x64-build
          

      - name: Edit permission
        run: chmod 777 $GITHUB_WORKSPACE/release-assets/EarthQuake-*
      
      - name: Upload Windows x64 Asset
        uses: svenstaro/upload-release-action@v2 
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/release-assets/EarthQuake-*
          overwrite: true
          tag: ${{ github.ref_name }}