name: Publish .NET App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_PATH: EarthQuake.Desktop/EarthQuake.Desktop.csproj
  OUTPUT_PATH: ./publish

jobs:
  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # .NET 7 以上を指定

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish for Windows x64
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime win-x64 --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/winx64
        
      - name: Publish for Windows x86
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime win-x86 --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/winx86
        
      - name: Publish for Linux x64
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime linux-x64 --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/linuxx64
        
      - name: Publish for Linux ARM32
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime linux-arm --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/linuxarm32
        
      - name: Publish for Linux ARM64
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime linux-arm64 --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/linuxarm64
        
      - name: Publish for macOS x64
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --runtime osx-x64 --self-contained -p:PublishSingleFile=true -o ${{ env.OUTPUT_PATH }}/osxx64
        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ${{ env.OUTPUT_PATH }}